runtime: python
entrypoint: gunicorn -b :$PORT main:app

env_variables:
  GOOGLE_CLOUD_PROJECT: My-First-Project

handlers:
  - url: /static
    static_dir: static/
  - url: /.*  
    script: auto



