runtime: python  # No comment here, just the runtime name
entrypoint: gunicorn -b :$PORT main:app

env_variables:
  GOOGLE_CLOUD_PROJECT: My-First-Project  # Optional, only if needed

handlers:
  - url: /static
    static_dir: static/
  - url: /.*  # All other routes will be handled by your app
    script: auto

