steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'functions'
  - 'deploy'
  - 'chatbot'
  - '--runtime'
  - 'python39'
  - '--trigger-http'
  - '--entry-point'
  - 'app'
  - '--source'
  - '.'
options:
  logging: CLOUD_LOGGING_ONLY
